language: node_js
node_js:
 - "node"
before_script: 
  - "psql -c \"CREATE DATABASE DB_TRAVIS;\" -U postgres"
  - "psql -c \"CREATE USER logicteca WITH PASSWORD '123';\" -U postgres"
env: 
  global: 
  - PGPORT=5432
services: 
  - postgresql
test: 
  adapter: postgresql
  database: testing_db